# Generated by Django 5.0.6 on 2024-06-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_singer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
