# Generated by Django 5.0.6 on 2024-06-30 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.singer'),
        ),
    ]
